# Generated by Django 6.0.6 on 2026-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_user_phone_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
