# Generated by Django 6.0.6 on 2026-06-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subscriptionplan_vendor_is_blocked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='is_blocked',
            new_name='Vendor_is_Unavailable',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='is_available',
            new_name='Vendor_is_available',
        ),
        migrations.RenameField(
            model_name='vendorsubscription',
            old_name='provider',
            new_name='Vendor',
        ),
    ]
